spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://192.168.10.87/blog?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      #生成初始化数据
    generate-ddl: true
    open-in-view: true
  mvc:
    favicon:
      enabled: true
    view:
      prefix: /
server:
  port: 8008

security:
  user:
    name: admin
    password: admin


